name: frontend
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  flutter_web_plugins:
    sdk: flutter
  get_it: ^7.7.0
  dio: ^5.7.0
  go_router: ^14.2.0
  equatable: ^2.0.5
  web: ^1.1.0
  intl: ^0.20.1
  retrofit: 4.0.3
  file_picker: ^8.1.7
  desktop_drop: ^0.5.0
  cross_file: ^0.3.5+1
  shared_models:
    path: ../shared_models
  super_clipboard: ^0.9.1
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: 7.0.8
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/tile.png
