name: shared_models
version: 0.1.0
environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  json_annotation: ^4.9.0
  equatable: ^2.0.5

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  test: ^1.25.0

